//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 07:46:09 PM CET 
//


package eu.driver_repository.namespace.dri;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.driver_repository.namespace.dri package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DateOfCollection_QNAME = new QName("http://www.driver-repository.eu/namespace/dri", "dateOfCollection");
    private final static QName _ObjIdentifier_QNAME = new QName("http://www.driver-repository.eu/namespace/dri", "objIdentifier");
    private final static QName _RepositoryId_QNAME = new QName("http://www.driver-repository.eu/namespace/dri", "repositoryId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.driver_repository.namespace.dri
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.driver-repository.eu/namespace/dri", name = "dateOfCollection")
    public JAXBElement<XMLGregorianCalendar> createDateOfCollection(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateOfCollection_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.driver-repository.eu/namespace/dri", name = "objIdentifier")
    public JAXBElement<String> createObjIdentifier(String value) {
        return new JAXBElement<String>(_ObjIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.driver-repository.eu/namespace/dri", name = "repositoryId")
    public JAXBElement<String> createRepositoryId(String value) {
        return new JAXBElement<String>(_RepositoryId_QNAME, String.class, null, value);
    }

}
