//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 07:46:09 PM CET 
//


package eu.openaire.namespace.oaf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="officialname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="englishname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="websiteurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contactemail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accessinfopackage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="namespaceprefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datasourcetypeui" type="{http://namespace.openaire.eu/oaf}classedSchemedElement"/>
 *         &lt;element name="datasourcetype" type="{http://namespace.openaire.eu/oaf}classedSchemedElement"/>
 *         &lt;element name="openairecompatibility" type="{http://namespace.openaire.eu/oaf}classedSchemedElement"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateofvalidation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="subjects" type="{http://namespace.openaire.eu/oaf}optionalClassedSchemedElement"/>
 *         &lt;element name="policies" type="{http://namespace.openaire.eu/oaf}namedIdElement"/>
 *         &lt;element name="logourl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="releasestartdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="releaseenddate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="missionstatementurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dataprovider" type="{http://namespace.openaire.eu/oaf}boolOrEmptyType"/>
 *         &lt;element name="serviceprovider" type="{http://namespace.openaire.eu/oaf}boolOrEmptyType"/>
 *         &lt;element name="databaseaccesstype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datauploadtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="databaseaccessrestriction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datauploadrestriction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="versioning" type="{http://namespace.openaire.eu/oaf}boolOrEmptyType"/>
 *         &lt;element name="citationguidelineurl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qualitymanagementkind" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pidsystems" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="certificates" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="originalId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="collectedfrom" type="{http://namespace.openaire.eu/oaf}namedIdElement"/>
 *         &lt;element name="pid" type="{http://namespace.openaire.eu/oaf}optionalClassedSchemedElement"/>
 *         &lt;element name="datainfo" type="{http://namespace.openaire.eu/oaf}datainfoType"/>
 *         &lt;element name="rels" type="{http://namespace.openaire.eu/oaf}relsType"/>
 *         &lt;element name="children">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="odnumberofitems" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="odnumberofitemsdate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="odlanguages" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="odcontenttypes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="odpolicies" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "officialnameOrEnglishnameOrWebsiteurl"
})
@XmlRootElement(name = "datasource")
public class Datasource {

    @XmlElementRefs({
        @XmlElementRef(name = "datasourcetype", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datasourcetypeui", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "databaseaccessrestriction", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datauploadtype", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "contactemail", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "odcontenttypes", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datainfo", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "englishname", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "children", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "namespaceprefix", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "logourl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "odpolicies", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "policies", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datauploadrestriction", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "versioning", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rels", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dataprovider", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "collectedfrom", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "qualitymanagementkind", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "accessinfopackage", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pidsystems", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subjects", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "longitude", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "certificates", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "databaseaccesstype", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "odnumberofitems", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "missionstatementurl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "openairecompatibility", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "officialname", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "latitude", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "websiteurl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "releasestartdate", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "odnumberofitemsdate", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "citationguidelineurl", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "serviceprovider", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dateofvalidation", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "releaseenddate", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "originalId", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pid", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "odlanguages", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> officialnameOrEnglishnameOrWebsiteurl;

    /**
     * Gets the value of the officialnameOrEnglishnameOrWebsiteurl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the officialnameOrEnglishnameOrWebsiteurl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOfficialnameOrEnglishnameOrWebsiteurl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link DatainfoType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Datasource.Children }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getOfficialnameOrEnglishnameOrWebsiteurl() {
        if (officialnameOrEnglishnameOrWebsiteurl == null) {
            officialnameOrEnglishnameOrWebsiteurl = new ArrayList<JAXBElement<?>>();
        }
        return this.officialnameOrEnglishnameOrWebsiteurl;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Children {

        @XmlValue
        protected String content;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

    }

}
