//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 07:46:09 PM CET 
//


package eu.openaire.namespace.oaf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about the provenance of this record. 
 * 
 * <p>Java class for datainfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="datainfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="inferred" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="deletedbyinference" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="trust" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inferenceprovenance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="provenanceaction" type="{http://namespace.openaire.eu/oaf}classedSchemedElement"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "datainfoType", propOrder = {
    "inferredOrDeletedbyinferenceOrTrust"
})
public class DatainfoType {

    @XmlElementRefs({
        @XmlElementRef(name = "trust", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "provenanceaction", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "deletedbyinference", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "inferenceprovenance", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "inferred", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> inferredOrDeletedbyinferenceOrTrust;

    /**
     * Gets the value of the inferredOrDeletedbyinferenceOrTrust property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inferredOrDeletedbyinferenceOrTrust property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInferredOrDeletedbyinferenceOrTrust().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getInferredOrDeletedbyinferenceOrTrust() {
        if (inferredOrDeletedbyinferenceOrTrust == null) {
            inferredOrDeletedbyinferenceOrTrust = new ArrayList<JAXBElement<?>>();
        }
        return this.inferredOrDeletedbyinferenceOrTrust;
    }

}
