//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 07:46:09 PM CET 
//


package eu.openaire.namespace.oaf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for instanceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="instanceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="licence" type="{http://namespace.openaire.eu/oaf}classedSchemedElement"/>
 *         &lt;element name="instancetype" type="{http://namespace.openaire.eu/oaf}classedSchemedElement"/>
 *         &lt;element name="hostedby" type="{http://namespace.openaire.eu/oaf}namedIdElement"/>
 *         &lt;element name="webresource" type="{http://namespace.openaire.eu/oaf}webresourceType" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "instanceType", propOrder = {
    "licenceOrInstancetypeOrHostedby"
})
public class InstanceType {

    @XmlElementRefs({
        @XmlElementRef(name = "licence", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "hostedby", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "webresource", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "instancetype", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> licenceOrInstancetypeOrHostedby;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the licenceOrInstancetypeOrHostedby property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the licenceOrInstancetypeOrHostedby property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLicenceOrInstancetypeOrHostedby().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}
     * {@link JAXBElement }{@code <}{@link WebresourceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getLicenceOrInstancetypeOrHostedby() {
        if (licenceOrInstancetypeOrHostedby == null) {
            licenceOrInstancetypeOrHostedby = new ArrayList<JAXBElement<?>>();
        }
        return this.licenceOrInstancetypeOrHostedby;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
