//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 07:46:09 PM CET 
//


package eu.openaire.namespace.oaf;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.openaire.namespace.oaf package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FundingTreeTypeFundingLevel2_QNAME = new QName("", "funding_level_2");
    private final static QName _FundingTreeTypeFundingLevel1_QNAME = new QName("", "funding_level_1");
    private final static QName _FundingTreeTypeFundingLevel0_QNAME = new QName("", "funding_level_0");
    private final static QName _ResultCountry_QNAME = new QName("", "country");
    private final static QName _ResultDateofacceptance_QNAME = new QName("", "dateofacceptance");
    private final static QName _ResultSubject_QNAME = new QName("", "subject");
    private final static QName _ResultMetadataversionnumber_QNAME = new QName("", "metadataversionnumber");
    private final static QName _ResultDescription_QNAME = new QName("", "description");
    private final static QName _ResultLanguage_QNAME = new QName("", "language");
    private final static QName _ResultPid_QNAME = new QName("", "pid");
    private final static QName _ResultSource_QNAME = new QName("", "source");
    private final static QName _ResultLastmetadataupdate_QNAME = new QName("", "lastmetadataupdate");
    private final static QName _ResultTitle_QNAME = new QName("", "title");
    private final static QName _ResultRels_QNAME = new QName("", "rels");
    private final static QName _ResultJournal_QNAME = new QName("", "journal");
    private final static QName _ResultRelevantdate_QNAME = new QName("", "relevantdate");
    private final static QName _ResultChildren_QNAME = new QName("", "children");
    private final static QName _ResultFulltext_QNAME = new QName("", "fulltext");
    private final static QName _ResultContext_QNAME = new QName("", "context");
    private final static QName _ResultStoragedate_QNAME = new QName("", "storagedate");
    private final static QName _ResultEmbargoenddate_QNAME = new QName("", "embargoenddate");
    private final static QName _ResultBestlicense_QNAME = new QName("", "bestlicense");
    private final static QName _ResultFormat_QNAME = new QName("", "format");
    private final static QName _ResultCollectedfrom_QNAME = new QName("", "collectedfrom");
    private final static QName _ResultResourcetype_QNAME = new QName("", "resourcetype");
    private final static QName _ResultVersion_QNAME = new QName("", "version");
    private final static QName _ResultResulttype_QNAME = new QName("", "resulttype");
    private final static QName _ResultSize_QNAME = new QName("", "size");
    private final static QName _ResultDatainfo_QNAME = new QName("", "datainfo");
    private final static QName _ResultPublisher_QNAME = new QName("", "publisher");
    private final static QName _ResultOriginalId_QNAME = new QName("", "originalId");
    private final static QName _ResultDevice_QNAME = new QName("", "device");
    private final static QName _DatainfoTypeTrust_QNAME = new QName("", "trust");
    private final static QName _DatainfoTypeProvenanceaction_QNAME = new QName("", "provenanceaction");
    private final static QName _DatainfoTypeInferenceprovenance_QNAME = new QName("", "inferenceprovenance");
    private final static QName _DatainfoTypeInferred_QNAME = new QName("", "inferred");
    private final static QName _DatainfoTypeDeletedbyinference_QNAME = new QName("", "deletedbyinference");
    private final static QName _PersonFirstname_QNAME = new QName("", "firstname");
    private final static QName _PersonSecondnames_QNAME = new QName("", "secondnames");
    private final static QName _PersonNationality_QNAME = new QName("", "nationality");
    private final static QName _PersonPhone_QNAME = new QName("", "phone");
    private final static QName _PersonAnchor_QNAME = new QName("", "anchor");
    private final static QName _PersonFullname_QNAME = new QName("", "fullname");
    private final static QName _PersonFax_QNAME = new QName("", "fax");
    private final static QName _PersonEmail_QNAME = new QName("", "email");
    private final static QName _DatasourceContactemail_QNAME = new QName("", "contactemail");
    private final static QName _DatasourceDatasourcetype_QNAME = new QName("", "datasourcetype");
    private final static QName _DatasourceMissionstatementurl_QNAME = new QName("", "missionstatementurl");
    private final static QName _DatasourceServiceprovider_QNAME = new QName("", "serviceprovider");
    private final static QName _DatasourceReleasestartdate_QNAME = new QName("", "releasestartdate");
    private final static QName _DatasourceVersioning_QNAME = new QName("", "versioning");
    private final static QName _DatasourceAccessinfopackage_QNAME = new QName("", "accessinfopackage");
    private final static QName _DatasourceLatitude_QNAME = new QName("", "latitude");
    private final static QName _DatasourcePolicies_QNAME = new QName("", "policies");
    private final static QName _DatasourceOdpolicies_QNAME = new QName("", "odpolicies");
    private final static QName _DatasourceOdnumberofitems_QNAME = new QName("", "odnumberofitems");
    private final static QName _DatasourceLogourl_QNAME = new QName("", "logourl");
    private final static QName _DatasourceEnglishname_QNAME = new QName("", "englishname");
    private final static QName _DatasourceNamespaceprefix_QNAME = new QName("", "namespaceprefix");
    private final static QName _DatasourceOpenairecompatibility_QNAME = new QName("", "openairecompatibility");
    private final static QName _DatasourceCitationguidelineurl_QNAME = new QName("", "citationguidelineurl");
    private final static QName _DatasourceDatabaseaccessrestriction_QNAME = new QName("", "databaseaccessrestriction");
    private final static QName _DatasourceOdnumberofitemsdate_QNAME = new QName("", "odnumberofitemsdate");
    private final static QName _DatasourceOfficialname_QNAME = new QName("", "officialname");
    private final static QName _DatasourceLongitude_QNAME = new QName("", "longitude");
    private final static QName _DatasourceDateofvalidation_QNAME = new QName("", "dateofvalidation");
    private final static QName _DatasourceOdcontenttypes_QNAME = new QName("", "odcontenttypes");
    private final static QName _DatasourcePidsystems_QNAME = new QName("", "pidsystems");
    private final static QName _DatasourceDatauploadtype_QNAME = new QName("", "datauploadtype");
    private final static QName _DatasourceReleaseenddate_QNAME = new QName("", "releaseenddate");
    private final static QName _DatasourceSubjects_QNAME = new QName("", "subjects");
    private final static QName _DatasourceDatasourcetypeui_QNAME = new QName("", "datasourcetypeui");
    private final static QName _DatasourceCertificates_QNAME = new QName("", "certificates");
    private final static QName _DatasourceWebsiteurl_QNAME = new QName("", "websiteurl");
    private final static QName _DatasourceQualitymanagementkind_QNAME = new QName("", "qualitymanagementkind");
    private final static QName _DatasourceDatauploadrestriction_QNAME = new QName("", "datauploadrestriction");
    private final static QName _DatasourceDataprovider_QNAME = new QName("", "dataprovider");
    private final static QName _DatasourceDatabaseaccesstype_QNAME = new QName("", "databaseaccesstype");
    private final static QName _DatasourceOdlanguages_QNAME = new QName("", "odlanguages");
    private final static QName _ProjectCode_QNAME = new QName("", "code");
    private final static QName _ProjectKeywords_QNAME = new QName("", "keywords");
    private final static QName _ProjectAcronym_QNAME = new QName("", "acronym");
    private final static QName _ProjectOamandatepublications_QNAME = new QName("", "oamandatepublications");
    private final static QName _ProjectCallidentifier_QNAME = new QName("", "callidentifier");
    private final static QName _ProjectFundingtree_QNAME = new QName("", "fundingtree");
    private final static QName _ProjectEcarticle293_QNAME = new QName("", "ecarticle29_3");
    private final static QName _ProjectStartdate_QNAME = new QName("", "startdate");
    private final static QName _ProjectDuration_QNAME = new QName("", "duration");
    private final static QName _ProjectEnddate_QNAME = new QName("", "enddate");
    private final static QName _ProjectContracttype_QNAME = new QName("", "contracttype");
    private final static QName _ProjectEcsc39_QNAME = new QName("", "ecsc39");
    private final static QName _OrganizationEcnonprofit_QNAME = new QName("", "ecnonprofit");
    private final static QName _OrganizationEclegalbody_QNAME = new QName("", "eclegalbody");
    private final static QName _OrganizationLegalname_QNAME = new QName("", "legalname");
    private final static QName _OrganizationLegalshortname_QNAME = new QName("", "legalshortname");
    private final static QName _OrganizationEclegalperson_QNAME = new QName("", "eclegalperson");
    private final static QName _OrganizationEcsmevalidated_QNAME = new QName("", "ecsmevalidated");
    private final static QName _OrganizationEcenterprise_QNAME = new QName("", "ecenterprise");
    private final static QName _OrganizationEcnutscode_QNAME = new QName("", "ecnutscode");
    private final static QName _OrganizationEcresearchorganization_QNAME = new QName("", "ecresearchorganization");
    private final static QName _OrganizationEcinternationalorganization_QNAME = new QName("", "ecinternationalorganization");
    private final static QName _OrganizationEcinternationalorganizationeurinterests_QNAME = new QName("", "ecinternationalorganizationeurinterests");
    private final static QName _OrganizationEchighereducation_QNAME = new QName("", "echighereducation");
    private final static QName _RelTypeFunding_QNAME = new QName("", "funding");
    private final static QName _RelTypeType_QNAME = new QName("", "type");
    private final static QName _RelTypeSimilarity_QNAME = new QName("", "similarity");
    private final static QName _RelTypeRanking_QNAME = new QName("", "ranking");
    private final static QName _RelTypeTo_QNAME = new QName("", "to");
    private final static QName _InstanceTypeLicence_QNAME = new QName("", "licence");
    private final static QName _InstanceTypeHostedby_QNAME = new QName("", "hostedby");
    private final static QName _InstanceTypeWebresource_QNAME = new QName("", "webresource");
    private final static QName _InstanceTypeInstancetype_QNAME = new QName("", "instancetype");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.openaire.namespace.oaf
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Datasource }
     * 
     */
    public Datasource createDatasource() {
        return new Datasource();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link ChildrenOrg }
     * 
     */
    public ChildrenOrg createChildrenOrg() {
        return new ChildrenOrg();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link OptionalClassedSchemedElement }
     * 
     */
    public OptionalClassedSchemedElement createOptionalClassedSchemedElement() {
        return new OptionalClassedSchemedElement();
    }

    /**
     * Create an instance of {@link ClassedSchemedElement }
     * 
     */
    public ClassedSchemedElement createClassedSchemedElement() {
        return new ClassedSchemedElement();
    }

    /**
     * Create an instance of {@link InferenceExtendedStringType }
     * 
     */
    public InferenceExtendedStringType createInferenceExtendedStringType() {
        return new InferenceExtendedStringType();
    }

    /**
     * Create an instance of {@link JournalType }
     * 
     */
    public JournalType createJournalType() {
        return new JournalType();
    }

    /**
     * Create an instance of {@link NamedIdElement }
     * 
     */
    public NamedIdElement createNamedIdElement() {
        return new NamedIdElement();
    }

    /**
     * Create an instance of {@link ContextType }
     * 
     */
    public ContextType createContextType() {
        return new ContextType();
    }

    /**
     * Create an instance of {@link DatainfoType }
     * 
     */
    public DatainfoType createDatainfoType() {
        return new DatainfoType();
    }

    /**
     * Create an instance of {@link RelsType }
     * 
     */
    public RelsType createRelsType() {
        return new RelsType();
    }

    /**
     * Create an instance of {@link ResultChildrenType }
     * 
     */
    public ResultChildrenType createResultChildrenType() {
        return new ResultChildrenType();
    }

    /**
     * Create an instance of {@link Person.Children }
     * 
     */
    public Person.Children createPersonChildren() {
        return new Person.Children();
    }

    /**
     * Create an instance of {@link Datasource.Children }
     * 
     */
    public Datasource.Children createDatasourceChildren() {
        return new Datasource.Children();
    }

    /**
     * Create an instance of {@link eu.openaire.namespace.oaf.Organization }
     * 
     */
    public eu.openaire.namespace.oaf.Organization createOrganization() {
        return new eu.openaire.namespace.oaf.Organization();
    }

    /**
     * Create an instance of {@link FundingTreeType }
     * 
     */
    public FundingTreeType createFundingTreeType() {
        return new FundingTreeType();
    }

    /**
     * Create an instance of {@link Project.Children }
     * 
     */
    public Project.Children createProjectChildren() {
        return new Project.Children();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link ExtraInfoType }
     * 
     */
    public ExtraInfoType createExtraInfoType() {
        return new ExtraInfoType();
    }

    /**
     * Create an instance of {@link RelToType }
     * 
     */
    public RelToType createRelToType() {
        return new RelToType();
    }

    /**
     * Create an instance of {@link WebresourceType }
     * 
     */
    public WebresourceType createWebresourceType() {
        return new WebresourceType();
    }

    /**
     * Create an instance of {@link ChildrenResult }
     * 
     */
    public ChildrenResult createChildrenResult() {
        return new ChildrenResult();
    }

    /**
     * Create an instance of {@link ConceptType }
     * 
     */
    public ConceptType createConceptType() {
        return new ConceptType();
    }

    /**
     * Create an instance of {@link FunderFlatType }
     * 
     */
    public FunderFlatType createFunderFlatType() {
        return new FunderFlatType();
    }

    /**
     * Create an instance of {@link RelType }
     * 
     */
    public RelType createRelType() {
        return new RelType();
    }

    /**
     * Create an instance of {@link NamedFundingLevel }
     * 
     */
    public NamedFundingLevel createNamedFundingLevel() {
        return new NamedFundingLevel();
    }

    /**
     * Create an instance of {@link FunderType }
     * 
     */
    public FunderType createFunderType() {
        return new FunderType();
    }

    /**
     * Create an instance of {@link ExternalreferenceType }
     * 
     */
    public ExternalreferenceType createExternalreferenceType() {
        return new ExternalreferenceType();
    }

    /**
     * Create an instance of {@link FundingFlatType }
     * 
     */
    public FundingFlatType createFundingFlatType() {
        return new FundingFlatType();
    }

    /**
     * Create an instance of {@link FundingType }
     * 
     */
    public FundingType createFundingType() {
        return new FundingType();
    }

    /**
     * Create an instance of {@link InstanceType }
     * 
     */
    public InstanceType createInstanceType() {
        return new InstanceType();
    }

    /**
     * Create an instance of {@link CategoryType }
     * 
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link FundingParentType }
     * 
     */
    public FundingParentType createFundingParentType() {
        return new FundingParentType();
    }

    /**
     * Create an instance of {@link LabeledIdElement }
     * 
     */
    public LabeledIdElement createLabeledIdElement() {
        return new LabeledIdElement();
    }

    /**
     * Create an instance of {@link InferenceExtendedBooleanType }
     * 
     */
    public InferenceExtendedBooleanType createInferenceExtendedBooleanType() {
        return new InferenceExtendedBooleanType();
    }

    /**
     * Create an instance of {@link ChildrenOrg.Organization }
     * 
     */
    public ChildrenOrg.Organization createChildrenOrgOrganization() {
        return new ChildrenOrg.Organization();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "funding_level_2", scope = FundingTreeType.class)
    public JAXBElement<FundingType> createFundingTreeTypeFundingLevel2(FundingType value) {
        return new JAXBElement<FundingType>(_FundingTreeTypeFundingLevel2_QNAME, FundingType.class, FundingTreeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "funding_level_1", scope = FundingTreeType.class)
    public JAXBElement<FundingType> createFundingTreeTypeFundingLevel1(FundingType value) {
        return new JAXBElement<FundingType>(_FundingTreeTypeFundingLevel1_QNAME, FundingType.class, FundingTreeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "funding_level_0", scope = FundingTreeType.class)
    public JAXBElement<FundingType> createFundingTreeTypeFundingLevel0(FundingType value) {
        return new JAXBElement<FundingType>(_FundingTreeTypeFundingLevel0_QNAME, FundingType.class, FundingTreeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country", scope = Result.class)
    public JAXBElement<ClassedSchemedElement> createResultCountry(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_ResultCountry_QNAME, ClassedSchemedElement.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InferenceExtendedStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dateofacceptance", scope = Result.class)
    public JAXBElement<InferenceExtendedStringType> createResultDateofacceptance(InferenceExtendedStringType value) {
        return new JAXBElement<InferenceExtendedStringType>(_ResultDateofacceptance_QNAME, InferenceExtendedStringType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subject", scope = Result.class)
    public JAXBElement<OptionalClassedSchemedElement> createResultSubject(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultSubject_QNAME, OptionalClassedSchemedElement.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "metadataversionnumber", scope = Result.class)
    public JAXBElement<String> createResultMetadataversionnumber(String value) {
        return new JAXBElement<String>(_ResultMetadataversionnumber_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description", scope = Result.class)
    public JAXBElement<String> createResultDescription(String value) {
        return new JAXBElement<String>(_ResultDescription_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "language", scope = Result.class)
    public JAXBElement<OptionalClassedSchemedElement> createResultLanguage(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultLanguage_QNAME, OptionalClassedSchemedElement.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pid", scope = Result.class)
    public JAXBElement<OptionalClassedSchemedElement> createResultPid(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultPid_QNAME, OptionalClassedSchemedElement.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source", scope = Result.class)
    public JAXBElement<String> createResultSource(String value) {
        return new JAXBElement<String>(_ResultSource_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastmetadataupdate", scope = Result.class)
    public JAXBElement<String> createResultLastmetadataupdate(String value) {
        return new JAXBElement<String>(_ResultLastmetadataupdate_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = Result.class)
    public JAXBElement<ClassedSchemedElement> createResultTitle(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_ResultTitle_QNAME, ClassedSchemedElement.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rels", scope = Result.class)
    public JAXBElement<RelsType> createResultRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JournalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "journal", scope = Result.class)
    public JAXBElement<JournalType> createResultJournal(JournalType value) {
        return new JAXBElement<JournalType>(_ResultJournal_QNAME, JournalType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relevantdate", scope = Result.class)
    public JAXBElement<OptionalClassedSchemedElement> createResultRelevantdate(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultRelevantdate_QNAME, OptionalClassedSchemedElement.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResultChildrenType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "children", scope = Result.class)
    public JAXBElement<ResultChildrenType> createResultChildren(ResultChildrenType value) {
        return new JAXBElement<ResultChildrenType>(_ResultChildren_QNAME, ResultChildrenType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InferenceExtendedStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fulltext", scope = Result.class)
    public JAXBElement<InferenceExtendedStringType> createResultFulltext(InferenceExtendedStringType value) {
        return new JAXBElement<InferenceExtendedStringType>(_ResultFulltext_QNAME, InferenceExtendedStringType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "context", scope = Result.class)
    public JAXBElement<ContextType> createResultContext(ContextType value) {
        return new JAXBElement<ContextType>(_ResultContext_QNAME, ContextType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "storagedate", scope = Result.class)
    public JAXBElement<String> createResultStoragedate(String value) {
        return new JAXBElement<String>(_ResultStoragedate_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "embargoenddate", scope = Result.class)
    public JAXBElement<String> createResultEmbargoenddate(String value) {
        return new JAXBElement<String>(_ResultEmbargoenddate_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bestlicense", scope = Result.class)
    public JAXBElement<ClassedSchemedElement> createResultBestlicense(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_ResultBestlicense_QNAME, ClassedSchemedElement.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "format", scope = Result.class)
    public JAXBElement<String> createResultFormat(String value) {
        return new JAXBElement<String>(_ResultFormat_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "collectedfrom", scope = Result.class)
    public JAXBElement<NamedIdElement> createResultCollectedfrom(NamedIdElement value) {
        return new JAXBElement<NamedIdElement>(_ResultCollectedfrom_QNAME, NamedIdElement.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resourcetype", scope = Result.class)
    public JAXBElement<OptionalClassedSchemedElement> createResultResourcetype(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultResourcetype_QNAME, OptionalClassedSchemedElement.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version", scope = Result.class)
    public JAXBElement<String> createResultVersion(String value) {
        return new JAXBElement<String>(_ResultVersion_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resulttype", scope = Result.class)
    public JAXBElement<ClassedSchemedElement> createResultResulttype(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_ResultResulttype_QNAME, ClassedSchemedElement.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "size", scope = Result.class)
    public JAXBElement<String> createResultSize(String value) {
        return new JAXBElement<String>(_ResultSize_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatainfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datainfo", scope = Result.class)
    public JAXBElement<DatainfoType> createResultDatainfo(DatainfoType value) {
        return new JAXBElement<DatainfoType>(_ResultDatainfo_QNAME, DatainfoType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InferenceExtendedStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publisher", scope = Result.class)
    public JAXBElement<InferenceExtendedStringType> createResultPublisher(InferenceExtendedStringType value) {
        return new JAXBElement<InferenceExtendedStringType>(_ResultPublisher_QNAME, InferenceExtendedStringType.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "originalId", scope = Result.class)
    public JAXBElement<String> createResultOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "device", scope = Result.class)
    public JAXBElement<String> createResultDevice(String value) {
        return new JAXBElement<String>(_ResultDevice_QNAME, String.class, Result.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dateofacceptance", scope = ChildrenResult.class)
    public JAXBElement<String> createChildrenResultDateofacceptance(String value) {
        return new JAXBElement<String>(_ResultDateofacceptance_QNAME, String.class, ChildrenResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publisher", scope = ChildrenResult.class)
    public JAXBElement<String> createChildrenResultPublisher(String value) {
        return new JAXBElement<String>(_ResultPublisher_QNAME, String.class, ChildrenResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = ChildrenResult.class)
    public JAXBElement<ClassedSchemedElement> createChildrenResultTitle(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_ResultTitle_QNAME, ClassedSchemedElement.class, ChildrenResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resulttype", scope = ChildrenResult.class)
    public JAXBElement<ClassedSchemedElement> createChildrenResultResulttype(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_ResultResulttype_QNAME, ClassedSchemedElement.class, ChildrenResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trust", scope = DatainfoType.class)
    public JAXBElement<String> createDatainfoTypeTrust(String value) {
        return new JAXBElement<String>(_DatainfoTypeTrust_QNAME, String.class, DatainfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "provenanceaction", scope = DatainfoType.class)
    public JAXBElement<ClassedSchemedElement> createDatainfoTypeProvenanceaction(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_DatainfoTypeProvenanceaction_QNAME, ClassedSchemedElement.class, DatainfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "inferenceprovenance", scope = DatainfoType.class)
    public JAXBElement<String> createDatainfoTypeInferenceprovenance(String value) {
        return new JAXBElement<String>(_DatainfoTypeInferenceprovenance_QNAME, String.class, DatainfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "inferred", scope = DatainfoType.class)
    public JAXBElement<Boolean> createDatainfoTypeInferred(Boolean value) {
        return new JAXBElement<Boolean>(_DatainfoTypeInferred_QNAME, Boolean.class, DatainfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deletedbyinference", scope = DatainfoType.class)
    public JAXBElement<Boolean> createDatainfoTypeDeletedbyinference(Boolean value) {
        return new JAXBElement<Boolean>(_DatainfoTypeDeletedbyinference_QNAME, Boolean.class, DatainfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "firstname", scope = Person.class)
    public JAXBElement<String> createPersonFirstname(String value) {
        return new JAXBElement<String>(_PersonFirstname_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "collectedfrom", scope = Person.class)
    public JAXBElement<NamedIdElement> createPersonCollectedfrom(NamedIdElement value) {
        return new JAXBElement<NamedIdElement>(_ResultCollectedfrom_QNAME, NamedIdElement.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "secondnames", scope = Person.class)
    public JAXBElement<String> createPersonSecondnames(String value) {
        return new JAXBElement<String>(_PersonSecondnames_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pid", scope = Person.class)
    public JAXBElement<OptionalClassedSchemedElement> createPersonPid(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultPid_QNAME, OptionalClassedSchemedElement.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rels", scope = Person.class)
    public JAXBElement<RelsType> createPersonRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nationality", scope = Person.class)
    public JAXBElement<OptionalClassedSchemedElement> createPersonNationality(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_PersonNationality_QNAME, OptionalClassedSchemedElement.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatainfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datainfo", scope = Person.class)
    public JAXBElement<DatainfoType> createPersonDatainfo(DatainfoType value) {
        return new JAXBElement<DatainfoType>(_ResultDatainfo_QNAME, DatainfoType.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "phone", scope = Person.class)
    public JAXBElement<String> createPersonPhone(String value) {
        return new JAXBElement<String>(_PersonPhone_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Person.Children }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "children", scope = Person.class)
    public JAXBElement<Person.Children> createPersonChildren(Person.Children value) {
        return new JAXBElement<Person.Children>(_ResultChildren_QNAME, Person.Children.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "anchor", scope = Person.class)
    public JAXBElement<Boolean> createPersonAnchor(Boolean value) {
        return new JAXBElement<Boolean>(_PersonAnchor_QNAME, Boolean.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fullname", scope = Person.class)
    public JAXBElement<String> createPersonFullname(String value) {
        return new JAXBElement<String>(_PersonFullname_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "originalId", scope = Person.class)
    public JAXBElement<String> createPersonOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fax", scope = Person.class)
    public JAXBElement<String> createPersonFax(String value) {
        return new JAXBElement<String>(_PersonFax_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "email", scope = Person.class)
    public JAXBElement<String> createPersonEmail(String value) {
        return new JAXBElement<String>(_PersonEmail_QNAME, String.class, Person.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contactemail", scope = Datasource.class)
    public JAXBElement<String> createDatasourceContactemail(String value) {
        return new JAXBElement<String>(_DatasourceContactemail_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datasourcetype", scope = Datasource.class)
    public JAXBElement<ClassedSchemedElement> createDatasourceDatasourcetype(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_DatasourceDatasourcetype_QNAME, ClassedSchemedElement.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "missionstatementurl", scope = Datasource.class)
    public JAXBElement<String> createDatasourceMissionstatementurl(String value) {
        return new JAXBElement<String>(_DatasourceMissionstatementurl_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serviceprovider", scope = Datasource.class)
    public JAXBElement<String> createDatasourceServiceprovider(String value) {
        return new JAXBElement<String>(_DatasourceServiceprovider_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "releasestartdate", scope = Datasource.class)
    public JAXBElement<String> createDatasourceReleasestartdate(String value) {
        return new JAXBElement<String>(_DatasourceReleasestartdate_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "versioning", scope = Datasource.class)
    public JAXBElement<String> createDatasourceVersioning(String value) {
        return new JAXBElement<String>(_DatasourceVersioning_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "accessinfopackage", scope = Datasource.class)
    public JAXBElement<String> createDatasourceAccessinfopackage(String value) {
        return new JAXBElement<String>(_DatasourceAccessinfopackage_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "latitude", scope = Datasource.class)
    public JAXBElement<String> createDatasourceLatitude(String value) {
        return new JAXBElement<String>(_DatasourceLatitude_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "policies", scope = Datasource.class)
    public JAXBElement<NamedIdElement> createDatasourcePolicies(NamedIdElement value) {
        return new JAXBElement<NamedIdElement>(_DatasourcePolicies_QNAME, NamedIdElement.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDescription(String value) {
        return new JAXBElement<String>(_ResultDescription_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "odpolicies", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOdpolicies(String value) {
        return new JAXBElement<String>(_DatasourceOdpolicies_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pid", scope = Datasource.class)
    public JAXBElement<OptionalClassedSchemedElement> createDatasourcePid(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultPid_QNAME, OptionalClassedSchemedElement.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "odnumberofitems", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOdnumberofitems(String value) {
        return new JAXBElement<String>(_DatasourceOdnumberofitems_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "logourl", scope = Datasource.class)
    public JAXBElement<String> createDatasourceLogourl(String value) {
        return new JAXBElement<String>(_DatasourceLogourl_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rels", scope = Datasource.class)
    public JAXBElement<RelsType> createDatasourceRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "englishname", scope = Datasource.class)
    public JAXBElement<String> createDatasourceEnglishname(String value) {
        return new JAXBElement<String>(_DatasourceEnglishname_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Datasource.Children }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "children", scope = Datasource.class)
    public JAXBElement<Datasource.Children> createDatasourceChildren(Datasource.Children value) {
        return new JAXBElement<Datasource.Children>(_ResultChildren_QNAME, Datasource.Children.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "namespaceprefix", scope = Datasource.class)
    public JAXBElement<String> createDatasourceNamespaceprefix(String value) {
        return new JAXBElement<String>(_DatasourceNamespaceprefix_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "openairecompatibility", scope = Datasource.class)
    public JAXBElement<ClassedSchemedElement> createDatasourceOpenairecompatibility(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_DatasourceOpenairecompatibility_QNAME, ClassedSchemedElement.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "citationguidelineurl", scope = Datasource.class)
    public JAXBElement<String> createDatasourceCitationguidelineurl(String value) {
        return new JAXBElement<String>(_DatasourceCitationguidelineurl_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "databaseaccessrestriction", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDatabaseaccessrestriction(String value) {
        return new JAXBElement<String>(_DatasourceDatabaseaccessrestriction_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "odnumberofitemsdate", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOdnumberofitemsdate(String value) {
        return new JAXBElement<String>(_DatasourceOdnumberofitemsdate_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "officialname", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOfficialname(String value) {
        return new JAXBElement<String>(_DatasourceOfficialname_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "longitude", scope = Datasource.class)
    public JAXBElement<String> createDatasourceLongitude(String value) {
        return new JAXBElement<String>(_DatasourceLongitude_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dateofvalidation", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDateofvalidation(String value) {
        return new JAXBElement<String>(_DatasourceDateofvalidation_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "odcontenttypes", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOdcontenttypes(String value) {
        return new JAXBElement<String>(_DatasourceOdcontenttypes_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pidsystems", scope = Datasource.class)
    public JAXBElement<String> createDatasourcePidsystems(String value) {
        return new JAXBElement<String>(_DatasourcePidsystems_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datauploadtype", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDatauploadtype(String value) {
        return new JAXBElement<String>(_DatasourceDatauploadtype_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "releaseenddate", scope = Datasource.class)
    public JAXBElement<String> createDatasourceReleaseenddate(String value) {
        return new JAXBElement<String>(_DatasourceReleaseenddate_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subjects", scope = Datasource.class)
    public JAXBElement<OptionalClassedSchemedElement> createDatasourceSubjects(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_DatasourceSubjects_QNAME, OptionalClassedSchemedElement.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "collectedfrom", scope = Datasource.class)
    public JAXBElement<NamedIdElement> createDatasourceCollectedfrom(NamedIdElement value) {
        return new JAXBElement<NamedIdElement>(_ResultCollectedfrom_QNAME, NamedIdElement.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datasourcetypeui", scope = Datasource.class)
    public JAXBElement<ClassedSchemedElement> createDatasourceDatasourcetypeui(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_DatasourceDatasourcetypeui_QNAME, ClassedSchemedElement.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "certificates", scope = Datasource.class)
    public JAXBElement<String> createDatasourceCertificates(String value) {
        return new JAXBElement<String>(_DatasourceCertificates_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatainfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datainfo", scope = Datasource.class)
    public JAXBElement<DatainfoType> createDatasourceDatainfo(DatainfoType value) {
        return new JAXBElement<DatainfoType>(_ResultDatainfo_QNAME, DatainfoType.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "websiteurl", scope = Datasource.class)
    public JAXBElement<String> createDatasourceWebsiteurl(String value) {
        return new JAXBElement<String>(_DatasourceWebsiteurl_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "qualitymanagementkind", scope = Datasource.class)
    public JAXBElement<String> createDatasourceQualitymanagementkind(String value) {
        return new JAXBElement<String>(_DatasourceQualitymanagementkind_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datauploadrestriction", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDatauploadrestriction(String value) {
        return new JAXBElement<String>(_DatasourceDatauploadrestriction_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "originalId", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataprovider", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDataprovider(String value) {
        return new JAXBElement<String>(_DatasourceDataprovider_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "databaseaccesstype", scope = Datasource.class)
    public JAXBElement<String> createDatasourceDatabaseaccesstype(String value) {
        return new JAXBElement<String>(_DatasourceDatabaseaccesstype_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "odlanguages", scope = Datasource.class)
    public JAXBElement<String> createDatasourceOdlanguages(String value) {
        return new JAXBElement<String>(_DatasourceOdlanguages_QNAME, String.class, Datasource.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "code", scope = Project.class)
    public JAXBElement<String> createProjectCode(String value) {
        return new JAXBElement<String>(_ProjectCode_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "keywords", scope = Project.class)
    public JAXBElement<String> createProjectKeywords(String value) {
        return new JAXBElement<String>(_ProjectKeywords_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "acronym", scope = Project.class)
    public JAXBElement<String> createProjectAcronym(String value) {
        return new JAXBElement<String>(_ProjectAcronym_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "oamandatepublications", scope = Project.class)
    public JAXBElement<Boolean> createProjectOamandatepublications(Boolean value) {
        return new JAXBElement<Boolean>(_ProjectOamandatepublications_QNAME, Boolean.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "callidentifier", scope = Project.class)
    public JAXBElement<String> createProjectCallidentifier(String value) {
        return new JAXBElement<String>(_ProjectCallidentifier_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subjects", scope = Project.class)
    public JAXBElement<OptionalClassedSchemedElement> createProjectSubjects(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_DatasourceSubjects_QNAME, OptionalClassedSchemedElement.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "collectedfrom", scope = Project.class)
    public JAXBElement<NamedIdElement> createProjectCollectedfrom(NamedIdElement value) {
        return new JAXBElement<NamedIdElement>(_ResultCollectedfrom_QNAME, NamedIdElement.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingTreeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fundingtree", scope = Project.class)
    public JAXBElement<FundingTreeType> createProjectFundingtree(FundingTreeType value) {
        return new JAXBElement<FundingTreeType>(_ProjectFundingtree_QNAME, FundingTreeType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ecarticle29_3", scope = Project.class)
    public JAXBElement<String> createProjectEcarticle293(String value) {
        return new JAXBElement<String>(_ProjectEcarticle293_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pid", scope = Project.class)
    public JAXBElement<OptionalClassedSchemedElement> createProjectPid(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultPid_QNAME, OptionalClassedSchemedElement.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = Project.class)
    public JAXBElement<String> createProjectTitle(String value) {
        return new JAXBElement<String>(_ResultTitle_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "startdate", scope = Project.class)
    public JAXBElement<String> createProjectStartdate(String value) {
        return new JAXBElement<String>(_ProjectStartdate_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rels", scope = Project.class)
    public JAXBElement<RelsType> createProjectRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "duration", scope = Project.class)
    public JAXBElement<String> createProjectDuration(String value) {
        return new JAXBElement<String>(_ProjectDuration_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "enddate", scope = Project.class)
    public JAXBElement<String> createProjectEnddate(String value) {
        return new JAXBElement<String>(_ProjectEnddate_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contracttype", scope = Project.class)
    public JAXBElement<OptionalClassedSchemedElement> createProjectContracttype(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ProjectContracttype_QNAME, OptionalClassedSchemedElement.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatainfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datainfo", scope = Project.class)
    public JAXBElement<DatainfoType> createProjectDatainfo(DatainfoType value) {
        return new JAXBElement<DatainfoType>(_ResultDatainfo_QNAME, DatainfoType.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Project.Children }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "children", scope = Project.class)
    public JAXBElement<Project.Children> createProjectChildren(Project.Children value) {
        return new JAXBElement<Project.Children>(_ResultChildren_QNAME, Project.Children.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ecsc39", scope = Project.class)
    public JAXBElement<String> createProjectEcsc39(String value) {
        return new JAXBElement<String>(_ProjectEcsc39_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "websiteurl", scope = Project.class)
    public JAXBElement<String> createProjectWebsiteurl(String value) {
        return new JAXBElement<String>(_DatasourceWebsiteurl_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "originalId", scope = Project.class)
    public JAXBElement<String> createProjectOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, Project.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<OptionalClassedSchemedElement> createOrganizationCountry(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultCountry_QNAME, OptionalClassedSchemedElement.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ecnonprofit", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationEcnonprofit(String value) {
        return new JAXBElement<String>(_OrganizationEcnonprofit_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eclegalbody", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationEclegalbody(String value) {
        return new JAXBElement<String>(_OrganizationEclegalbody_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "legalname", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationLegalname(String value) {
        return new JAXBElement<String>(_OrganizationLegalname_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "legalshortname", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationLegalshortname(String value) {
        return new JAXBElement<String>(_OrganizationLegalshortname_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "eclegalperson", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationEclegalperson(String value) {
        return new JAXBElement<String>(_OrganizationEclegalperson_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "collectedfrom", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<NamedIdElement> createOrganizationCollectedfrom(NamedIdElement value) {
        return new JAXBElement<NamedIdElement>(_ResultCollectedfrom_QNAME, NamedIdElement.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pid", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<OptionalClassedSchemedElement> createOrganizationPid(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultPid_QNAME, OptionalClassedSchemedElement.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ecsmevalidated", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationEcsmevalidated(String value) {
        return new JAXBElement<String>(_OrganizationEcsmevalidated_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "logourl", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationLogourl(String value) {
        return new JAXBElement<String>(_DatasourceLogourl_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rels", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<RelsType> createOrganizationRels(RelsType value) {
        return new JAXBElement<RelsType>(_ResultRels_QNAME, RelsType.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ecenterprise", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationEcenterprise(String value) {
        return new JAXBElement<String>(_OrganizationEcenterprise_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ecnutscode", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationEcnutscode(String value) {
        return new JAXBElement<String>(_OrganizationEcnutscode_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ecresearchorganization", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationEcresearchorganization(String value) {
        return new JAXBElement<String>(_OrganizationEcresearchorganization_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatainfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datainfo", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<DatainfoType> createOrganizationDatainfo(DatainfoType value) {
        return new JAXBElement<DatainfoType>(_ResultDatainfo_QNAME, DatainfoType.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ecinternationalorganization", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationEcinternationalorganization(String value) {
        return new JAXBElement<String>(_OrganizationEcinternationalorganization_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChildrenOrg }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "children", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<ChildrenOrg> createOrganizationChildren(ChildrenOrg value) {
        return new JAXBElement<ChildrenOrg>(_ResultChildren_QNAME, ChildrenOrg.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "websiteurl", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationWebsiteurl(String value) {
        return new JAXBElement<String>(_DatasourceWebsiteurl_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ecinternationalorganizationeurinterests", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationEcinternationalorganizationeurinterests(String value) {
        return new JAXBElement<String>(_OrganizationEcinternationalorganizationeurinterests_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "originalId", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationOriginalId(String value) {
        return new JAXBElement<String>(_ResultOriginalId_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "echighereducation", scope = eu.openaire.namespace.oaf.Organization.class)
    public JAXBElement<String> createOrganizationEchighereducation(String value) {
        return new JAXBElement<String>(_OrganizationEchighereducation_QNAME, String.class, eu.openaire.namespace.oaf.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country", scope = ChildrenOrg.Organization.class)
    public JAXBElement<ClassedSchemedElement> createChildrenOrgOrganizationCountry(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_ResultCountry_QNAME, ClassedSchemedElement.class, ChildrenOrg.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "legalname", scope = ChildrenOrg.Organization.class)
    public JAXBElement<String> createChildrenOrgOrganizationLegalname(String value) {
        return new JAXBElement<String>(_OrganizationLegalname_QNAME, String.class, ChildrenOrg.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "websiteurl", scope = ChildrenOrg.Organization.class)
    public JAXBElement<String> createChildrenOrgOrganizationWebsiteurl(String value) {
        return new JAXBElement<String>(_DatasourceWebsiteurl_QNAME, String.class, ChildrenOrg.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "legalshortname", scope = ChildrenOrg.Organization.class)
    public JAXBElement<String> createChildrenOrgOrganizationLegalshortname(String value) {
        return new JAXBElement<String>(_OrganizationLegalshortname_QNAME, String.class, ChildrenOrg.Organization.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datasourcetype", scope = RelType.class)
    public JAXBElement<ClassedSchemedElement> createRelTypeDatasourcetype(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_DatasourceDatasourcetype_QNAME, ClassedSchemedElement.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country", scope = RelType.class)
    public JAXBElement<OptionalClassedSchemedElement> createRelTypeCountry(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultCountry_QNAME, OptionalClassedSchemedElement.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundingFlatType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "funding", scope = RelType.class)
    public JAXBElement<FundingFlatType> createRelTypeFunding(FundingFlatType value) {
        return new JAXBElement<FundingFlatType>(_RelTypeFunding_QNAME, FundingFlatType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "code", scope = RelType.class)
    public JAXBElement<String> createRelTypeCode(String value) {
        return new JAXBElement<String>(_ProjectCode_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dateofacceptance", scope = RelType.class)
    public JAXBElement<String> createRelTypeDateofacceptance(String value) {
        return new JAXBElement<String>(_ResultDateofacceptance_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "acronym", scope = RelType.class)
    public JAXBElement<String> createRelTypeAcronym(String value) {
        return new JAXBElement<String>(_ProjectAcronym_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "legalname", scope = RelType.class)
    public JAXBElement<String> createRelTypeLegalname(String value) {
        return new JAXBElement<String>(_OrganizationLegalname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "legalshortname", scope = RelType.class)
    public JAXBElement<String> createRelTypeLegalshortname(String value) {
        return new JAXBElement<String>(_OrganizationLegalshortname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title", scope = RelType.class)
    public JAXBElement<OptionalClassedSchemedElement> createRelTypeTitle(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ResultTitle_QNAME, OptionalClassedSchemedElement.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type", scope = RelType.class)
    public JAXBElement<String> createRelTypeType(String value) {
        return new JAXBElement<String>(_RelTypeType_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "datasourcetypeui", scope = RelType.class)
    public JAXBElement<ClassedSchemedElement> createRelTypeDatasourcetypeui(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_DatasourceDatasourcetypeui_QNAME, ClassedSchemedElement.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resulttype", scope = RelType.class)
    public JAXBElement<ClassedSchemedElement> createRelTypeResulttype(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_ResultResulttype_QNAME, ClassedSchemedElement.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contracttype", scope = RelType.class)
    public JAXBElement<OptionalClassedSchemedElement> createRelTypeContracttype(OptionalClassedSchemedElement value) {
        return new JAXBElement<OptionalClassedSchemedElement>(_ProjectContracttype_QNAME, OptionalClassedSchemedElement.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "phone", scope = RelType.class)
    public JAXBElement<String> createRelTypePhone(String value) {
        return new JAXBElement<String>(_PersonPhone_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "websiteurl", scope = RelType.class)
    public JAXBElement<Object> createRelTypeWebsiteurl(Object value) {
        return new JAXBElement<Object>(_DatasourceWebsiteurl_QNAME, Object.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "similarity", scope = RelType.class)
    public JAXBElement<Double> createRelTypeSimilarity(Double value) {
        return new JAXBElement<Double>(_RelTypeSimilarity_QNAME, Double.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publisher", scope = RelType.class)
    public JAXBElement<String> createRelTypePublisher(String value) {
        return new JAXBElement<String>(_ResultPublisher_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ranking", scope = RelType.class)
    public JAXBElement<BigInteger> createRelTypeRanking(BigInteger value) {
        return new JAXBElement<BigInteger>(_RelTypeRanking_QNAME, BigInteger.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelToType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "to", scope = RelType.class)
    public JAXBElement<RelToType> createRelTypeTo(RelToType value) {
        return new JAXBElement<RelToType>(_RelTypeTo_QNAME, RelToType.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fullname", scope = RelType.class)
    public JAXBElement<String> createRelTypeFullname(String value) {
        return new JAXBElement<String>(_PersonFullname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fax", scope = RelType.class)
    public JAXBElement<String> createRelTypeFax(String value) {
        return new JAXBElement<String>(_PersonFax_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "email", scope = RelType.class)
    public JAXBElement<String> createRelTypeEmail(String value) {
        return new JAXBElement<String>(_PersonEmail_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "officialname", scope = RelType.class)
    public JAXBElement<String> createRelTypeOfficialname(String value) {
        return new JAXBElement<String>(_DatasourceOfficialname_QNAME, String.class, RelType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "licence", scope = InstanceType.class)
    public JAXBElement<ClassedSchemedElement> createInstanceTypeLicence(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_InstanceTypeLicence_QNAME, ClassedSchemedElement.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hostedby", scope = InstanceType.class)
    public JAXBElement<NamedIdElement> createInstanceTypeHostedby(NamedIdElement value) {
        return new JAXBElement<NamedIdElement>(_InstanceTypeHostedby_QNAME, NamedIdElement.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebresourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "webresource", scope = InstanceType.class)
    public JAXBElement<WebresourceType> createInstanceTypeWebresource(WebresourceType value) {
        return new JAXBElement<WebresourceType>(_InstanceTypeWebresource_QNAME, WebresourceType.class, InstanceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassedSchemedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "instancetype", scope = InstanceType.class)
    public JAXBElement<ClassedSchemedElement> createInstanceTypeInstancetype(ClassedSchemedElement value) {
        return new JAXBElement<ClassedSchemedElement>(_InstanceTypeInstancetype_QNAME, ClassedSchemedElement.class, InstanceType.class, value);
    }

}
