//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.08 at 07:46:09 PM CET 
//


package eu.openaire.namespace.oaf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="secondnames" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fullname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nationality" type="{http://namespace.openaire.eu/oaf}optionalClassedSchemedElement"/>
 *         &lt;element name="originalId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="collectedfrom" type="{http://namespace.openaire.eu/oaf}namedIdElement" maxOccurs="unbounded"/>
 *         &lt;element name="pid" type="{http://namespace.openaire.eu/oaf}optionalClassedSchemedElement"/>
 *         &lt;element name="anchor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="datainfo" type="{http://namespace.openaire.eu/oaf}datainfoType"/>
 *         &lt;element name="rels" type="{http://namespace.openaire.eu/oaf}relsType"/>
 *         &lt;element name="children">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "firstnameOrSecondnamesOrFullname"
})
@XmlRootElement(name = "person")
public class Person {

    @XmlElementRefs({
        @XmlElementRef(name = "children", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rels", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "firstname", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "pid", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fullname", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "secondnames", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fax", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "anchor", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "phone", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "nationality", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "collectedfrom", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "originalId", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "datainfo", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "email", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> firstnameOrSecondnamesOrFullname;

    /**
     * Gets the value of the firstnameOrSecondnamesOrFullname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the firstnameOrSecondnamesOrFullname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFirstnameOrSecondnamesOrFullname().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Person.Children }{@code >}
     * {@link JAXBElement }{@code <}{@link RelsType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link OptionalClassedSchemedElement }{@code >}
     * {@link JAXBElement }{@code <}{@link NamedIdElement }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link DatainfoType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getFirstnameOrSecondnamesOrFullname() {
        if (firstnameOrSecondnamesOrFullname == null) {
            firstnameOrSecondnamesOrFullname = new ArrayList<JAXBElement<?>>();
        }
        return this.firstnameOrSecondnamesOrFullname;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Children {

        @XmlValue
        protected String content;

        /**
         * Gets the value of the content property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContent() {
            return content;
        }

        /**
         * Sets the value of the content property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContent(String value) {
            this.content = value;
        }

    }

}
